
CREATE TABLE IF NOT EXISTS Users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(40),
    login     VARCHAR(30),
    name      VARCHAR(50),
    birthdate DATE,
    created   timestamp,
    updated   timestamp
);

CREATE TABLE IF NOT EXISTS Rating
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(5),
    description varchar(150)
);

CREATE TABLE IF NOT EXISTS Genre
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(15)
);


CREATE TABLE IF NOT EXISTS Film
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(50),
    description  varchar(100),
    release_date DATE,
    duration     INTEGER,
    rating_id    INTEGER REFERENCES rating (id),
    created      timestamp,
    updated      timestamp
);


CREATE TABLE IF NOT EXISTS Friendship
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    created   timestamp,
    updated   timestamp
);

CREATE TABLE IF NOT EXISTS Likes
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES Film (id),
    user_id INTEGER REFERENCES users (id),
    created timestamp,
    updated timestamp
);

CREATE TABLE IF NOT EXISTS FilmGenre
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id  INTEGER REFERENCES Film (id),
    genre_id INTEGER REFERENCES Genre (id),
    created  timestamp,
    updated  timestamp
);
